import Head from 'next/head'
import HeaderBar from '../components/HeaderBar.js'
import Footer from '../components/Footer.js'

function Layout(props) {

    return (
      <>
        {/* TODO: change after finishe project */}
        <Head>
          <title>Frank Hsu - homepage</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <HeaderBar />
        {props.children}
        <Footer />
      </>
    )
}

export default Layout;